# Generated by Django 4.2.2 on 2023-07-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_languagedb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydb',
            name='Language',
        ),
    ]
