# Generated by Django 4.2.2 on 2023-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_languagedb_categorydb_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='languagedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='Language',
        ),
    ]
