# Generated by Django 4.2.2 on 2023-07-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_languagedb_remove_categorydb_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=50, null=True)),
                ('Language', models.CharField(blank=True, max_length=50, null=True)),
                ('MovieName', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Thumbnail', models.ImageField(upload_to='Thumb')),
            ],
        ),
    ]
