# Generated by Django 4.2.2 on 2023-07-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
