# Generated by Django 4.2.2 on 2023-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_registerdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkoutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Contact', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
